org: samadarshad
app: serverless-todo-app
service: serverless-todo-app
plugins:
  - serverless-webpack
  - serverless-iam-roles-per-function
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-s3-local
provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-west-2'}
  environment:
    accountId: 324941539183
    TODOS_TABLE: todos-${self:provider.stage}
    TODO_INDEX: TodoIdIndex
    LAST_CREATED_INDEX: LastCreated
    # DISABLE_XRAY_TRACING: true # for local only
    # _X_AMZN_TRACE_ID: 0        # for local only
    ATTACHMENTS_BUCKET: todos-${self:provider.environment.accountId}-attachments-${self:provider.stage}
    SIGNED_URL_EXPIRATION: 300
    LOCAL_S3_HOST: localhost
    LOCAL_S3_PORT: 4569
  tracing:
    lambda: true
    apiGateway: true
functions:
  - ${file(functions.yml)}
resources:  
  - ${file(resources.yml)} 
custom:
  serverless-offline:
    httpPort: 3003
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: true
    stages:
      - dev
    seed:
      test:
        sources:
          - table: ${self:provider.environment.TODOS_TABLE}
            sources: [./items.json]  
  s3:
    host: ${self:provider.environment.LOCAL_S3_HOST}
    port: ${self:provider.environment.LOCAL_S3_PORT}
    directory: /tmp
    allowMismatchedSignatures: true